const CryptoJS = require("crypto-js");

//Any 64character key generated by Openssl rsa
// On bash > openssl rand -hex 32
var key = 'a317cf49dd42b84271b5029cc5db17884c0ff3ed6f3e3b8fdb47c8e9d1458d3d';

module.exports.encryptData = function (plaintext) {
    let ciphertext = CryptoJS.AES.encrypt(plaintext, key);
    return ciphertext.toString();
}

module.exports.decryptData = function (ciphertext) {
    let bytes  = CryptoJS.AES.decrypt(ciphertext.toString(), key);
    let plaintext = bytes.toString(CryptoJS.enc.Utf8);
    return plaintext;
}
